# the filter currently checks for words that are 3 or more characters.
---
ass: "*ss"
asses: "*ss*s"
asshole: "*ssh*l*"
assholes: "*ssh*l*s"
bastard: b*st*rd
biatch: b**tch
bitch: b*tch
bitcher: b*tch*r
bitchers: b*tch*rs
bitches: b*tch*s
bitchin: b*tch*n
bitching: b*tch*ng
bollocks: b*ll*cks
cock: c*ck
cocks: c*cks
cocksuck: c*cks*ck
cocksucked: c*cks*ck*d
cocksucker: c*cks*ck*r
cocksucking: c*cks*ck*ng
cocksucks: c*cks*cks
cunt: c*nt
cuntlick: c*ntl*ck
cuntlicker: c*ntl*ck*r
cuntlicking: c*ntl*ck*ng
cunts: c*nts
fag: f*g
fagging: f*gg*ng
faggot: f*gg*t
faggs: f*ggs
fagot: f*g*t
fagots: f*g*ts
fags: f*gs
fingerfuck: f*ng*rf*ck
fingerfucked: f*ng*rf*ck*d
fingerfucker: f*ng*rf*ck*r
fingerfuckers: f*ng*rf*ck*rs
fingerfucking: f*ng*rf*ck*ng
fingerfucks: f*ng*rf*cks
fistfuck: f*stf*ck
fistfucked: f*stf*ck*d
fistfucker: f*stf*ck*r
fistfuckers: f*stf*ck*rs
fistfucking: f*stf*ck*ng
fistfuckings: f*stf*ck*ngs
fistfucks: f*stf*cks
fuck: f*ck
fucked: f*ck*d
fucker: f*ck*r
fuckers: f*ck*rs
fuckin: f*ck*n
fucking: f*ck*ng
fuckings: f*ck*ngs
fuckme: f*ckm*
fucks: f*cks
fudgepacker: f*dg*p*ck*r
fuk: f*k
fuks: f*ks
gook: g**k
kock: k*ck
mothafuck: m*th*f*ck
mothafucka: m*th*f*ck*
mothafuckas: m*th*f*ck*s
mothafuckaz: m*th*f*ck*z
mothafucked: m*th*f*ck*d
mothafucker: m*th*f*ck*r
mothafuckers: m*th*f*ck*rs
mothafuckin: m*th*f*ck*n
mothafucking: m*th*f*ck*ng
mothafuckings: m*th*f*ck*ngs
mothafucks: m*th*f*cks
motherfuck: m*th*rf*ck
motherfucked: m*th*rf*ck*d
motherfucker: m*th*rf*ck*r
motherfuckers: m*th*rf*ck*rs
motherfuckin: m*th*rf*ck*n
motherfucking: m*th*rf*ck*ng
motherfuckings: m*th*rf*ck*ngs
motherfucks: m*th*rf*cks
niger: n*gg*r
nigger: n*gg*r
niggers: n*gg*rs
phuk: ph*k
phuked: ph*k*d
phuking: ph*k*ng
phukked: ph*kk*d
phukking: ph*kk*ng
phuks: ph*ks
shit: sh*t
shited: sh*t*d
shitfull: sh*tf*ll
shiting: sh*t*ng
shitings: sh*t*ngs
shits: sh*ts
shitted: sh*tt*d
shitter: sh*tt*r
shitters: sh*tt*rs
shitting: sh*tt*ng
shittings: sh*tt*ngs
shitty: sh*tty
shity: sh*tty
shyte: sh*t*